sudo: false

language: node
node_js:
  - "node"

# APT is required to install Chrome
addons:
  apt:
    update: true

# Cache yarn
cache:
  yarn: true

before_install:
  # Install Chrome, required to build an XPI file
  - sudo apt-get install -y chromium

  # Install NodeJS
  - nvm install node
  - npm install -g yarn web-ext

install:
  # Download Yarn assets using lockfile
  - yarn install --frozen-lockfile

script:
  # Lint Javascript
  - make lint

  # Make Chrome extension (xpi)
  - make chrome

  # Make Firefox extension (zip)3
  - make firefox

  # Copy release files
  - mv "$( git rev-parse --show-toplevel 2>/dev/null)"/dist/*.zip "$( git rev-parse --show-toplevel 2>/dev/null)"

matrix:
  fast_finish: true

deploy:
  provider: releases
  api_key:
    secure: OLJXPBOPIffi0nr+md8WePZB0BCmlQ6+AE8mIdDmvG4f62JpgyEPW/VVThMN+53jEGGP8FZUKDtAP+6Rb4WUNtF8NNYb6vD0fcNofoNIEkyfBSQgcYid/30OTjog3XoOjo6JMGuweQq5GRcJ6woPaKD6YyipYA/LWSkcZJcrCrWeCzP1LxDOwvjJwzHP3PGbFAzPoqaGoBQ42CmMOuDXOraRQjtv2DMWztMqaDK2sM10PzdvIyrip2dSh1J2JkttkvCrFFUwKPrXm7WZs/JIzdQD/txYQLOx6gcEpAnzD3UIjQpZQzrPCozhlgycVB/6YKz8dKNZTptFZY6TkvkBYDbhUWbq8OVUa2FFjGAF5OeZw5MJjvtkc4NRHNW4jnc4w2h4+BuGq56EneNMzK34PKe7b5QBnCFOmGfJsXxcOXavsTdn7jN+Xu/w2DwHqaWXMGaT5XrwGotj0f705BeV/jpetGpLtqXcWKJRU85UU7pfV4D+aaH5UwDl5WbtoY67S6M/ITlfay1NCf51R4UzzoRH6NkS4cL2cgPO7EftvaWArBq29GrOVlSF9c4nL7qfyTBL2xbEQ558tzvtlAUGavam+UXz7O5PPhk+0PCKoOKPlqLAl68uDFtGAt2dnca324yWckUXqtuV8L96EYktlTScFNB0Hr0YCgdsUg1cYng=
  file:
    - "doot-doot-linux-x64.zip"
    - "doot-doot-win32-x64.zip"
  skip_cleanup: true
  on:
    tags: true
