sudo: false

language: node
node_js:
  - "node"

# Cache yarn
cache:
  yarn: true

before_install:
  # Install NodeJS
  - nvm install node
  - npm install -g yarn

install:
  # Download Yarn assets using lockfile
  - yarn install --frozen-lockfile

script:
  # Lint Javascript
  - make lint

  # Make Chrome extension (xpi)
  - make chrome

  # Make Firefox extension (zip)3
  - make firefox

  # Move and rename files as <name>-unsigned
  - cp ./dist/*.zip "./born-to-be-alive--unsigned.zip"
  - cp ./dist/*.crx "./born-to-be-alive--unsigned.crx"

matrix:
  fast_finish: true

deploy:
  provider: releases
  api_key:
    secure: dXbGI9Fk6FRoXF9+n3hwyeOHsHTzAeu1npAyhH6X3X3RDE5lC/YPGTCZ/c44woLZJkfpA+Th7ohYCmqjlDGI6bWvVF4V60PhGPokskqBuvK6UBH8pMSPSoimEuD7nHM7QKOxzRmSlrK3dVqNn/C+/U+0AmYKZETG4s5mYl7fLisnU4trl98xN96Efc8Qm3QjdIDQVG25NVDl2rbcruGhmb9GG0I3zwKraV4Fbrd/XzfsQNc4Vmb0Xk8RuAca5o5scWSrwO8zZXRJo8gLyc4c1hu+AgOg0ke5JTb9+6RLkeGRAOUGkIXeg8/02+My0YQJTauVHyXxGGI5CDLN9yXHDBSjAPvjQrnNHWzSoAn2oJxmoRPQ0wt44J6ICOVZP296jLs1Ges8opOOBA2cxciaLzxpM5fFNSsFMDi71TQS8blrEYTR0E68fBRhB9+UH9X5xraykEwGz+8lwX3n1jkD47bV6JKTvTmEAAObOc6EudCXk8FLPQ8rVrg3swQXGnizGebPanmfrvc+Ze73WaLa21Tf+Imp/KFU5zK9DqEkMtTSh3xeTwcEqD61kYMY0HgKdfXC+w7FaWGIrA+WzbKOpCr3emOTtGBJ8YYGPb4XEBONxYCpLYLZkoyZ8IjFmavcHh3emeAlUnPR2wssB5EWVvk0kmoZc/ISMbwkIuG0dHQ=
  file:
    - "born-to-be-alive--unsigned.zip"
    - "born-to-be-alive--unsigned.crx"
  skip_cleanup: true
  on:
    tags: true
